### ISSUE TITLE
COFH Dependencies deprecated

### ISSUE THREAD

**Issue by mindforger** [RedGear/RedGearCore#4]
i am getting mod sorting issues when using your morebackpacks together with the latest (stable) forestry and thermal expansion. i tracked the error down to red gear included with more backpacks and got told on IRC it's a deprecated COFH nergy API included in your mod.

a log is not sufficient as it has no crashlog only stating very unspecific "mod sorting error" and a lotof work to trace down all references and removing all COFH api based mods until i hit this core mod

**Comment by MagmaSlime123** [comment]
> API updated in Core: 2.2.0

Delete your stuff if your not updating it. Give it to other people if you won't.
